### ISSUE TITLE
Add support for dict type

### ISSUE THREAD

**Issue by thergbway** [ZeroPointSystem/Flurry#1]
Do you have a python-like dict type? It is the same as your statement {...}. I guess It will be userful.

**Comment by ZeroPointSystem** [comment]
@thergbway It looks like a dict type from Python, but in this case it's a closure (anonymous function WITHOUT ANY ARGS)

Something like this: 

ref acceptor: ({}) -> {} = block -> block()

acceptor({ println "Hello closure!" })
